# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:

# Common Tasks

- task: DotNetCoreCLI@2
  displayName: 'Restore All'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build All'
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test All'
  inputs:
    command: test
    projects: '**/*test*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# API Tasks

- task: DotNetCoreCLI@2
  displayName: 'Publish Api'
  inputs:
    command: publish
    projects: '**/ProjectName.Api.csproj'
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

# APP Tasks

- task: DotNetCoreCLI@2
  displayName: 'Publish App'
  inputs:
    command: publish
    projects: '**/ProjectName.App.csproj'
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

# Artifacts

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: ProjectNameArtifacts